### ISSUE TITLE
Homework Week 7

### ISSUE THREAD

**Issue by ptums** [johnreda/trainschedule#1]
Hey man nice job on the homework! I know first hand it was difficult. What was the ultimate issue with the code and what was your solution?

**Comment by johnreda** [comment]
Ultimately, there were a few major issues. For one, the organization of things made some stuff work and other things not. I also was missing a few lines of code to handle some of the time events, and some of my math was off.

Overall, I got pretty close leading up to class, and between your help and Ahmed’s help, it was the first time I was able to submit a fully completed homework assignment!

Thanks!
